# Generated by Django 5.0.4 on 2024-04-07 13:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InflationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1979), django.core.validators.MaxValueValidator(2200)])),
                ('rate', models.DecimalField(decimal_places=5, max_digits=20)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddConstraint(
            model_name='inflationrate',
            constraint=models.UniqueConstraint(models.F('year'), models.F('month'), name='un_year_month_apiinflationrates'),
        ),
    ]
